<?php
error_reporting(0);
include('header.php');
include('config.php');

$status=$conn->real_escape_string($_POST["status"]);
$firstname=$conn->real_escape_string($_POST["firstname"]);
$amount=$conn->real_escape_string($_POST["amount"]);
$txnid=$conn->real_escape_string($_POST["txnid"]);
$posted_hash=$conn->real_escape_string($_POST["hash"]);
$key=$conn->real_escape_string($_POST["key"]);
$productinfo=$conn->real_escape_string($_POST["productinfo"]);
$email=$conn->real_escape_string($_POST["email"]);
$udf1=$conn->real_escape_string($_POST["udf1"]);
$udf2=$conn->real_escape_string($_POST["udf2"]);
$date2=date('Y-m-d');
$salt="";

If (isset($_POST["additionalCharges"])) {
       $additionalCharges=$_POST["additionalCharges"];
        $retHashSeq = $additionalCharges.'|'.$salt.'|'.$status.'|||||||||'.$udf2.'|'.$udf1.'|'.$email.'|'.$firstname.'|'.$productinfo.'|'.$amount.'|'.$txnid.'|'.$key;
        
                  }
  else {    

        $retHashSeq = $salt.'|'.$status.'|||||||||'.$udf2.'|'.$udf1.'|'.$email.'|'.$firstname.'|'.$productinfo.'|'.$amount.'|'.$txnid.'|'.$key;

         }
     $hash = hash("sha512", $retHashSeq);
     
       if ($hash != $posted_hash) {
         echo "Invalid Transaction. Please try again";
       }
     else {
               

$sql = "UPDATE exam_fee_payment SET status='$status' WHERE orderid='$txnid'";
mysqli_query($conn, $sql);
//echo  $sql;
$sqlup = "UPDATE exam_fee SET fee_status='$status' WHERE txnid='$txnid'";
mysqli_query($conn, $sqlup);
//echo  $sqlup;
$sqlup1 = "UPDATE apply_student_db SET status='$status' WHERE orderid='$txnid'";
mysqli_query($conn, $sqlup1);

$sqlselects = "SELECT * from `exam_fee_payment` where `orderid`='$txnid'"; 
                 $exeselects = mysqli_query($conn,$sqlselects) or die(mysql_error());
              //$row1 = mysqli_fetch_array($exe1);
              //echo $row1['orderid'];
 while($rowselects = mysqli_fetch_array($exeselects))
                {

 $regno=$rowselects['regno'];

$sqlup12 = "UPDATE student_master SET STATUS='$status' WHERE ENROLMENT='$regno'";
mysqli_query($conn, $sqlup12);

}

//echo  $sqlup1;
$sql1 = "INSERT INTO exam_payment_history(orderid,status,amount,date2)VALUES ('$txnid','$status','$amount','$date2')";
//echo $sql1;
mysqli_query($conn, $sql1);
}           
?>
<?php
$sqlselect = "SELECT * from `exam_fee_payment` where `orderid`='$txnid'"; 
$exeselect = mysqli_query($conn,$sqlselect) or die(mysql_error());

$rowselect = mysqli_fetch_array($exeselect);
                
                  $to=$rowselect['email'];
                  $student=$rowselect['student'];
                   $regno=$rowselect['regno'];
                  $mobile=$rowselect['mobile'];
                  $pd=$rowselect['paid_date'];
                  $newpd = date("d-m-Y", strtotime($pd)); 
                  $name = 'Alagappa University';
                  $subject = 'ALU - Examination Payment Regards';
                  $message =$status;
                

require '/usr/share/php/libphp-phpmailer/class.phpmailer.php';
require '/usr/share/php/libphp-phpmailer/class.smtp.php';
$mail = new PHPMailer;
$mail->setFrom('infoalumis@gmail.com');
$mail->addAddress($to);
$mail->Subject = 'ALU - Examination Payment Regards';
$mail->Body = '<h3>Payment Details</h3>
       <table width="100%" style=" border:1px solid #ccc;">
      <tbody><tr>  
                <td colspan="2"><img src="http://mis.alagappauniversity.ac.in/header.png" width="100%" alt="Header Image"></td>  
              </tr>
              <tr> 
              <td colspan="2" height="30"><center><u><strong>Examination Payment Receipt</strong></u></center></td>  
              </tr>
              <tr>  
                <td height="30"><b>Leaning Centre Code</b></td> 
                <td>'."  $student ".'</td>  
              </tr>
              
             <tr>  
                <td height="30"><b>Mobile Number</b></td> 
                <td>'." $mobile ". '</td> 
              </tr>
            <tr>  
                <td height="30"><b>Transaction ID</b></td> 
                 <td>'." $txnid ".'</td>   
            </tr>
            <tr>  
                <td height="30"><b>Status</b></td> 
                <td>'."  $status ".'</td> 
            </tr>  
                    
            <tr>  
                <td height="30"><b>Amount</b></td> 
                <td>'."  $amount ".'</td>  
            </tr>
             <tr>          
                <td height="30" ><b>Transaction Made Date</b></td> 
                <td>'."  $newpd ".'</td>  
            </tr>
          
          </table>
          <p>&nbsp;</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = '';
$mail->Password = '';
$sending_status = 1;
do {
    if (!$mail->send()) {
        $sending_status++;
        //echo 'Email is not sent.';
       // echo 'Email error: ' . $mail->ErrorInfo.$sending_status;
    } else {
  $sending_status = 1;
       // echo 'Email has been sent.'.$sending_status;
    }
} while ($sending_status != 1 && $sending_status <= 5);

?>


     
<html>
<head>
        <!--Twitter Bootstrap resources-->
        <link href="layout/styles/bootstrap-combined.min.css" rel="stylesheet">
        <script src="layout/styles/bootstrap.min1.js"></script>
        <link href="layout/styles/bootstrap.no-icons.min.css" rel="stylesheet">

        <style type="text/css">
          .center {
           float: none;
           margin-left: auto;
           margin-right: auto; 
          }
        </style>
</head>

<body><section id="intro1"></section>   
 <main id="main">
<section id="about1" class="section-bg">
      <div class="container-fluid">
       <?php include 'stud_menu.php'; ?>
    <div class="span7 center" id="print">
      <table class="table table-striped table-hover" border="1" style="color: black"> 
      
            <tbody>
              <tr> 
              <tr>  
                <td colspan="2"><img src="<?php echo $path; ?>/hostel-payment/images/header.png" width="100%" alt="Header Image"></td>  
              </tr> 
                <td colspan="2" height="30"><center><u><strong>Examination Fee Receipt</strong></u></center></td>  
              </tr>
               <?php
               $sql1 = "SELECT * from `exam_fee_payment` where `orderid`= '$txnid'"; 
                 $exe1 = mysqli_query($conn,$sql1) or die(mysql_error());
           

                 $row1 = mysqli_fetch_array($exe1);
                
                    ?>
               <tr>  
                <td height="30"><b>Centre Code</b></td> 
                <td><?php echo $row1['student']; ?></td>  
              </tr>
             
            <tr>  
                <td height="30"><b>e-Mail ID</b></td> 
                <td><?php echo $row1['email']; ?></td>  
              </tr>
              <tr>  
                <td height="30"><b>Mobile Number</b></td> 
                <td><?php echo $row1['mobile'];  ?></td>  
              </tr>
            <tr>  
                <td height="30"><b>OrderId</b></td> 
                <td><?php echo $txnid ?></td>  
            </tr>
            <tr>  
                <td height="30"><b>Status</b></td> 
                <td><?php  echo $status ?></td>  
            </tr>       
            <tr>  
                <td height="30"><b>Amount</b></td> 
                <td><?php echo $amount ?></td>  
            </tr>
             <tr>          
                <td height="30" ><b>Paid Date</b></td> 
                <td><?php $pd=$row1['paid_date']; $newpd = date("d-m-Y", strtotime($pd)); echo $newpd; ?></td>  
            </tr>
           
            
          </table> 
    </div><center><input type='button' id='btn' value='PRINT' onclick='printDiv();' style="margin: 10px;"></center></div></tbody></table></div></div></section></main>
</body>
</html>
<script>
function printDiv() 
{

  var divToPrint=document.getElementById('print');

  var newWin=window.open('','Print-Window');

  newWin.document.open();

  newWin.document.write('<html><body onload="window.print()">'+divToPrint.innerHTML+'</body></html>');

  newWin.document.close();

  setTimeout(function(){newWin.close();},10);

}
</script>
<?php
include('footer.php');
?>

